import react,{ useState , useEffect} from "react";
import {useLocation} from "react-router-dom";
import {useNavigate} from "react-router-dom";
import "../App.css";

function IteneraryOptionsPage(){
    const location = useLocation();
    const navigate =  useNavigate();
    // storing al the ifnromation collected form previous pages.
    const {destination , startDate , endDate , cities , selectedTravelTypes ,
        totalBudget , accomodationBudget , commuteBudget} = location.state|| {};
    // creating a state that stores all the itenerariesbeign generated by groq.
    const [iteneraries , setIteneraries] = useState<any[]>([]);

    // a function that will help to store the selected itenerary in the local storage:
    function sotreitenerary(itenerary:any , index:number){
        const inteneraryId = itenerary.id ?? index+1;
        localStorage.setItem("selecteditenerary" , itenerary); //storing the itenerary locally in the user's system

    //     now navigating to the itenerary page.
        navigate(`itinerary/${itenerary.id}` , {
            state:{
                itenerary
            }
        });

    }

    // sending all the important data to the backend's endpoint (post route) so that
    // backend can send the data to Groq api and help generate an itenerary.
    useEffect(()=>{
        const fetchitenerary = async() =>{
            try{
                const response = await fetch('http://localhost:5001/api/generate-itenerary' , {
                    method:'POST',
                    headers:{
                        'Content-Type':'application/json',
                    },
                    body:JSON.stringify({
                        destination,
                        startDate,
                        endDate ,
                        cities ,
                        selectedTravelTypes ,
                        totalBudget ,
                        accomodationBudget ,
                        commuteBudget
                    })
                });
                const data = await response.json();

                console.log("Complete backend response:", data);
                console.log("Type of data:", typeof data);
                console.log("data.message:", data.message);
                console.log("Type of data.message:", typeof data.message);

                let parsedData;

                if (typeof data.message === "string") {
                    parsedData = JSON.parse(data.message);
                } else if (data.message && typeof data.message === "object") {
                    parsedData = data.message;
                } else {
                    parsedData = data;
                }

                console.log("Parsed data:", parsedData);
                console.log("Itineraries array:", parsedData.itineraries);
                console.log(
                    "Is itineraries an array?",
                    Array.isArray(parsedData.itineraries)
                );

                if (!Array.isArray(parsedData.itineraries)) {
                    throw new Error("No itineraries array found in backend response");
                }

                setIteneraries(parsedData.itineraries);


            }catch (error) {
                console.error("Error generating itineraries:", error);
            }
        };
        fetchitenerary();
        }, []
    )
    return(
        <div>
            <div className="Page_Heading">
                <h1>Itenerary options</h1>
                <p>Number of itineraries: {iteneraries.length}</p>
            </div>
            <div className="itinerary-options-container">
                {iteneraries.map((itinerary, index) => (
                    <div className="itinerary-option-card" key={itinerary.id ?? index}>
        <span className="itinerary-number">
        Option {index + 1}
        </span>

                        <h2>{itinerary.title}</h2>

                        <p className="itinerary-summary">
                            {itinerary.summary}
                        </p>

                        <div className="itinerary-information">
                            <div>
                                <span>Duration</span>
                                <strong>{itinerary.days?.length ?? 0} days</strong>
                            </div>

                            <div>
                                <span>Estimated cost</span>
                                <strong>
                                    {itinerary.currency} {itinerary.estimatedCost}
                                </strong>
                            </div>
                        </div>

                        <div className="itinerary-highlights">
                            <h3>Highlights</h3>

                            <ul>
                                {itinerary.highlights
                                    ?.slice(0, 3)
                                    .map((highlight: string, highlightIndex: number) => (
                                        <li key={highlightIndex}>{highlight}</li>
                                    ))}
                            </ul>
                        </div>

                        <button
                            onClick={() =>
                                navigate(`/itinerary/${itinerary.id ?? index + 1}`, {
                                    state: {
                                        itinerary
                                    }
                                })
                            }
                        >
                            View full itinerary
                        </button>
                    </div>
                ))}
            </div>
        </div>
    )
}

export default IteneraryOptionsPage